apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include "busimporter.labels" . | nindent 4 }}
type: Opaque
data:
  THINGSBOARD_USERNAME: {{ .Values.env.tbUser | b64enc | quote }}
  THINGSBOARD_PASSWORD: {{ .Values.env.tbPassword | b64enc | quote }}
  SUBSCRIPTION_ID: {{ .Values.env.subscriptionId | b64enc | quote }}
  TOKEN_SERVICE_CLIENT_ID: {{ .Values.env.clientId | b64enc | quote }}
  TOKEN_SERVICE_CLIENT_SECRET: {{ .Values.env.clientSecret | b64enc | quote }}